---
title: "Introduction to R: Tidyverse"
author: "Erin Grand"
date: "Oct 14, 2017"
output: ioslides_presentation
---

# Introduction to R: Data Manipulation
Focusing on packages found in tidyverse


## Packages
Download tidyverse:
Imports: dplyr, ggplot2, lubricate, readr, readxl, stringr, tibble, tidyr, magrittr
if you're using multiple packages make sure you're loading them in the right order
```{r}
library(readxl)
library(tidyverse)
```


## Learn to think in Code
How to do you currently think about a task in excel or tableau? Learn how to translate and use that process in code.

1. What is your process for creating a pivot table?
1. What is your process for creating a new column?
1. How do you sort things?

--


## SPLIT APPLY COMBINE
1.	Split up the original data (this can be any format including data frames, lists, arrays, matrices, vectors),
2.	Apply existing or custom functions to it, and
3.	Combine the results in the same or different format.

This will come back in a later lesson when we look at `PURR` and functional programing.

##  Five Most Important DPLYR Functions/Verbs
1.	Filter
2.	Select
3.	Arrange
4.	Mutate
5.	Group by, Summarize (Summarise)


## Filter
Task: filter the IA data to only include NY 8th grade students Math tests. This way you'll only looking at Regents test takers.


## Select

## Arrange

## Mutate

## Group by